# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Verein zur Förderung mehrsprachiger digitaler Schulungsformate 
email: info@traintheworld.eu
description: >- # this means to ignore newlines until "baseurl:"
  Unser Verein fördert mehrsprachige digitale Schulungsformate in Europa, identifiziert und deckt Bildungs-, Beratungs- und Orientierungsbedarfe in der Erwachsenenbildung und der digitalen mehrsprachigen Kompetenzentwicklung. Wir untersuchen Spracherkennung und digitale Übersetzungsmethoden, entwickeln passende Lösungen und tragen zur Professionalisierung von Bildungsinstitutionen bei. Wir fördern Inklusion, Gleichheit und Nicht-Diskriminierung in Europa.
baseurl: "" # the subpath of your site, e.g. /blog
url: "traintheworld.eu" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed


